@startuml
'https://plantuml.com/state-diagram

hide empty description
scale 350 width
skinparam State {
  BorderColor violet
  BackgroundColor<<active>> lightblue
}

[*] -up-> pending : enqueue
note on link
  client
end note
pending -left-> active : dequeue
note on link
  processor
end note

state processed
state completed
state archived
archived: retry count exceeded or
archived: skip retry
state retry
retry: retry_at
state scheduled
scheduled: scheduled_at

state active {
  [*] --> processing <<active>>
  processing --> pending : requeue (server abort)
  processing --> failed : error
  processing --> timedOut
  processing --> cancelled : cancel
  note on link
    pub-sub
  end note

  processing --> processed : done
  processing --> completed : done (with retention)

  state failed <<active>>
  state timedOut <<active>>
  state cancelled <<active>>

  failed --> retry_or_archive
  timedOut --> retry_or_archive
  cancelled --> retry_or_archive

  state retry_or_archive <<active>>
  note right of retry_or_archive
    also executed by recoverer
    which polls deadlines exceeded
  end note
  retry_or_archive --> archived
  retry_or_archive --> retry
}
note top of active
  processor
end note

retry --> pending
note on link
  forwarder
end note

scheduled --> pending
note on link
  forwarder
end note

'completed --> [*]
processed --> [*]
completed --> [*]
note on link
  retention period
  elapsed
end note
archived --> [*]

@enduml